/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root.tsx'
import { Route as IndexRouteImport } from './routes/index.tsx'
import { Route as BlogThemesAndStylesIndexRouteImport } from './routes/blog/themesAndStyles/index.tsx'
import { Route as BlogJeremyIndexRouteImport } from './routes/blog/jeremy/index.tsx'
import { Route as BlogDoingCoolThingsWithMarkdown2IndexRouteImport } from './routes/blog/doingCoolThingsWithMarkdown2/index.tsx'
import { Route as BlogDoingCoolThingsWithMarkdownIndexRouteImport } from './routes/blog/doingCoolThingsWithMarkdown/index.tsx'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogThemesAndStylesIndexRoute =
  BlogThemesAndStylesIndexRouteImport.update({
    id: '/blog/themesAndStyles/',
    path: '/blog/themesAndStyles/',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogJeremyIndexRoute = BlogJeremyIndexRouteImport.update({
  id: '/blog/jeremy/',
  path: '/blog/jeremy/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogDoingCoolThingsWithMarkdown2IndexRoute =
  BlogDoingCoolThingsWithMarkdown2IndexRouteImport.update({
    id: '/blog/doingCoolThingsWithMarkdown2/',
    path: '/blog/doingCoolThingsWithMarkdown2/',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogDoingCoolThingsWithMarkdownIndexRoute =
  BlogDoingCoolThingsWithMarkdownIndexRouteImport.update({
    id: '/blog/doingCoolThingsWithMarkdown/',
    path: '/blog/doingCoolThingsWithMarkdown/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog/doingCoolThingsWithMarkdown': typeof BlogDoingCoolThingsWithMarkdownIndexRoute
  '/blog/doingCoolThingsWithMarkdown2': typeof BlogDoingCoolThingsWithMarkdown2IndexRoute
  '/blog/jeremy': typeof BlogJeremyIndexRoute
  '/blog/themesAndStyles': typeof BlogThemesAndStylesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog/doingCoolThingsWithMarkdown': typeof BlogDoingCoolThingsWithMarkdownIndexRoute
  '/blog/doingCoolThingsWithMarkdown2': typeof BlogDoingCoolThingsWithMarkdown2IndexRoute
  '/blog/jeremy': typeof BlogJeremyIndexRoute
  '/blog/themesAndStyles': typeof BlogThemesAndStylesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog/doingCoolThingsWithMarkdown/': typeof BlogDoingCoolThingsWithMarkdownIndexRoute
  '/blog/doingCoolThingsWithMarkdown2/': typeof BlogDoingCoolThingsWithMarkdown2IndexRoute
  '/blog/jeremy/': typeof BlogJeremyIndexRoute
  '/blog/themesAndStyles/': typeof BlogThemesAndStylesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog/doingCoolThingsWithMarkdown'
    | '/blog/doingCoolThingsWithMarkdown2'
    | '/blog/jeremy'
    | '/blog/themesAndStyles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog/doingCoolThingsWithMarkdown'
    | '/blog/doingCoolThingsWithMarkdown2'
    | '/blog/jeremy'
    | '/blog/themesAndStyles'
  id:
    | '__root__'
    | '/'
    | '/blog/doingCoolThingsWithMarkdown/'
    | '/blog/doingCoolThingsWithMarkdown2/'
    | '/blog/jeremy/'
    | '/blog/themesAndStyles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogDoingCoolThingsWithMarkdownIndexRoute: typeof BlogDoingCoolThingsWithMarkdownIndexRoute
  BlogDoingCoolThingsWithMarkdown2IndexRoute: typeof BlogDoingCoolThingsWithMarkdown2IndexRoute
  BlogJeremyIndexRoute: typeof BlogJeremyIndexRoute
  BlogThemesAndStylesIndexRoute: typeof BlogThemesAndStylesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/themesAndStyles/': {
      id: '/blog/themesAndStyles/'
      path: '/blog/themesAndStyles'
      fullPath: '/blog/themesAndStyles'
      preLoaderRoute: typeof BlogThemesAndStylesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/jeremy/': {
      id: '/blog/jeremy/'
      path: '/blog/jeremy'
      fullPath: '/blog/jeremy'
      preLoaderRoute: typeof BlogJeremyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/doingCoolThingsWithMarkdown2/': {
      id: '/blog/doingCoolThingsWithMarkdown2/'
      path: '/blog/doingCoolThingsWithMarkdown2'
      fullPath: '/blog/doingCoolThingsWithMarkdown2'
      preLoaderRoute: typeof BlogDoingCoolThingsWithMarkdown2IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/doingCoolThingsWithMarkdown/': {
      id: '/blog/doingCoolThingsWithMarkdown/'
      path: '/blog/doingCoolThingsWithMarkdown'
      fullPath: '/blog/doingCoolThingsWithMarkdown'
      preLoaderRoute: typeof BlogDoingCoolThingsWithMarkdownIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogDoingCoolThingsWithMarkdownIndexRoute:
    BlogDoingCoolThingsWithMarkdownIndexRoute,
  BlogDoingCoolThingsWithMarkdown2IndexRoute:
    BlogDoingCoolThingsWithMarkdown2IndexRoute,
  BlogJeremyIndexRoute: BlogJeremyIndexRoute,
  BlogThemesAndStylesIndexRoute: BlogThemesAndStylesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
